---
- name: Installation von Apache2
  hosts: matrix-app-01
  become: true
  vars_files: ./vars/credentials.yaml

  tasks:
    - name: Update packete und quellen
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Traefik + Lego Entfernen
      block:
        - name: Lego Deinstallieren
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /usr/local/bin/lego
            - /tmp/lego
            - /tmp/lego.tar.gz

        - name: Prüfe ob Traefik noch läuft
          ansible.builtin.systemd:
            name: traefik
          register: traefik_status

        - name: Stoppe Traefik
          ansible.builtin.service:
            name: traefik
            state: stopped
            enabled: false
          when: traefik_status.status.ActiveState == "active"

        - name: Traefik und dateien löschen
          ansible.builtin.file:
            state: absent
            path: "{{ item }}"
          loop:
            - /etc/traefik/dynamic/matrix.yml
            - /etc/systemd/system/traefik.service
            - /etc/traefik/traefik.yml
            - /usr/local/bin/traefik
            - /tmp/traefik
            - /tmp/traefik.tat.gz

        - name: Traefik vezeichnisse löschen
          ansible.builtin.file:
            state: absent
            path: "{{ item }}"
          loop:
            - /etc/traefik
            - /var/lib/traefik

        - name: Lösche Traefik benutzer
          ansible.builtin.user:
            name: traefik
            state: absent

        - name: Lösche Traefik gruppe
          ansible.builtin.group:
            name: traefik
            state: absent

    - name: Apache Installieren
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      register: apahce2_installed

    - name: Apache2 Module aktivieren
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy
        - proxy_http
        - headers
        - ssl
        - md
        - watchdog

    - name: vhost datei für apache2 anlegen
      ansible.builtin.file:
        path: /etc/apache2/sites-available/matrix.conf
        owner: root
        group: root
        mode: "0644"
        state: touch
      register: matrix_config_creadet

    - name: Template übertragen
      ansible.builtin.template:
        src: ./templates/matrix.conf.j2
        dest: /etc/apache2/sites-available/matrix.conf
      when: matrix_config_creadet.exist

    - name: Apache Default-Site deaktivieren
      ansible.builtin.command:
        argv:
          - a2dissite
          - 000-default.conf
      register: apache_default_site
      changed_when: "'Site 000-default disabled' in apache_default_site.stdout"

    - name: Matrix Site aktivieren
      ansible.builtin.command:
        argv:
          - a2ensite
          - matrix.conf
      register: apache_matrix_site
      changed_when: "'Enabling site matrix' in apache_matrix_site.stdout"

    - name: Apache neu starten
      ansible.builtin.systemd_service:
        name: apache2
        state: restarted
        enabled: true
