---
- name: Installation und einruchtung der CA.
  hosts: matrix-ca-02
  become: true
  vars_files:
    - ./vars/credentials.yaml
  tasks:
    - name: Installation von Paketen
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - curl
        - apt-transport-https
        - vim
        - rsync
        - lsb-release
        - gpg
        - ca-certificates
        - acl
        - openssl
        - python3-debian

    - name: Import quelle
      tags: test
      become: true
      ansible.builtin.deb822_repository:
        name: smallstep
        types:
          - deb
        uris:
          - https://packages.smallstep.com/stable/debian
        suites:
          - debs
        components:
          - main
        signed_by: https://packages.smallstep.com/keys/apt/repo-signing-key.gpg
        state: present
      register: smallstep_repo

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
      when: smallstep_repo.changed

    - name: Install Step-CA
      ansible.builtin.apt:
        name:
          - step-cli
          - step-ca
        state: present

    - name: CA User anlegen
      become: true
      ansible.builtin.user:
        name: step-ca
        system: true
        home: /var/lib/step-ca
        create_home: true
        shell: /usr/sbin/nologin

    - name: PW File anlegen
      become: true
      become_user: step-ca
      ansible.builtin.file:
        path: /var/lib/step-ca/passwort.txt
        mode: "600"
        owner: step-ca
        group: step-ca
        state: touch

    - name: Passwort datei für Step-CA Admin
      become: true
      ansible.builtin.template:
        dest: /var/lib/step-ca/passwort.txt
        src: ./templates/password.js2
        mode: "600"
        group: step-ca
        owner: step-ca

    - name: CA initialisieren
      become: true
      become_user: step-ca
      ansible.builtin.command:
        argv:
          - step
          - ca
          - init
          - --deployment-type
          - standalone
          - --name
          - DJT Internal CA
          - --dns
          - ca.lan
          - --address
          - :8443
          - --provisioner
          - ca-admin
          - --password-file
          - /var/lib/step-ca/passwort.txt
          - --provisioner-password-file
          - /var/lib/step-ca/passwort.txt
        creates: /var/lib/step-ca/.step/config/ca.json
      environment:
        STEPPATH: /var/lib/step-ca/.step

    - name: Installation des Service
      become: true
      ansible.builtin.template:
        src: ./templates/step-ca.service.js2
        dest: /etc/systemd/system/step-ca.service
        owner: root
        group: root
        mode: "0644"

    - name: Aktiviere und starte step-ca.service
      become: true
      ansible.builtin.systemd:
        name: step-ca
        enabled: true
        state: started

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart step-ca
      become: true
      ansible.builtin.systemd:
        name: step-ca
        state: restarted

    - name: Fingerprint erzeugen
      become: true
      become_user: step-ca
      ansible.builtin.command:
        argv:
          - step
          - certificate
          - fingerprint
          - /var/lib/step-ca/.step/certs/root_ca.crt
      environment:
        STEPPATH: /var/lib/step-ca/.step
      register: fprint

    - name: Fingerprint in datei schreiben
      ansible.builtin.copy:
        content: "{{ fprint.stdout }}\n"
        dest: "/home/{{ ansible_user }}/fprint.txt"
        mode: "0644"

    - name: datei zwichen partken
      ansible.builtin.fetch:
        src: "/home/{{ ansible_user }}/fprint.txt"
        dest: /tmp/
        flat: true
      delegate_to: matrix-ca-01

    - name: transfer zu matrix-app-01
      ansible.builtin.copy:
        src: /tmp/fprint.txt
        dest: /home/{{ ansible_user }}/fprint.txt
      delegate_to: matrix-app-01

    - name: update ca-admin
      notify: restart stepca
      become: true
      become_user: step-ca
      environment:
        HOME: /var/lib/step-ca
      ansible.builtin.command:
        argv:
          - step
          - ca
          - provisioner
          - update
          - ca-admin
          - --x509-max-dur
          - 8760h
          - --x509-default-dur
          - 2160h
          - --ca-url
          - https://ca.lan
          - --root
          - /var/lib/step-ca/.step/certs/root_ca.crt

    - name: Aktuelle ca.json einlesen
      ansible.builtin.slurp:
        src: /var/lib/step-ca/.step/config/ca.json
      register: ca_json_raw
      no_log: true

    - name: CRL Konfiguration erzeugen
      ansible.builtin.set_fact:
        ca_json_config: >-
          {{
            (ca_json_raw.content | b64decode | from_json)
            | combine(
              {
                'insecureAddress': ':9001',
                'crl': {
                  'enabled': true,
                  'idpURL': 'http://ca.lan:9001/1.0/crl'
                }
              },
              recursive=True
            )          
          }}
      no_log: true

    - name: CRL in ca.json Konfiguration
      ansible.builtin.copy:
        content: "{{ ca_json_config | to_nice_json }}\n"
        dest: /var/lib/step-ca/.step/config/ca.json
        owner: step-ca
        group: step-ca
        mode: "0600"
      no_log: true

    - name: Intermediate Tepmplate anlegen
      ansible.builtin.template:
        src: ./templates/intermediate.tpl.j2
        dest: /var/lib/step-ca/.step/intermediate.tpl
        owner: step-ca
        group: step-ca
        mode: "0600"

    - name: Prüfen ob CRL Intermediate bereits erzuegt wurde.
      ansible.builtin.stat:
        path: /var/lib/step-ca/.step/intermediate-crl-created
      register: intermediate_crl_markere

    - name: Intermediate CA mit CRL Distribution Point erzeugen.
      become: true
      become_user: step-ca
      ansible.builtin.command:
        argv:
          - step
          - certificate
          - create
          - --template
          - /var/lib/step-ca/.step/intermediate.tpl
          - --ca
          - /var/lib/step-ca/.step/certs/root_ca.crt
          - --ca-key
          - /var/lib/step-ca/.step/secrets/root_ca.key
          - --ca-password-file
          - /var/lib/step-ca/passwort.txt
          - --password-file
          - /var/lib/step-ca/passwort.txt
          - --not-after
          - 43800h
          - --force
          - DJT Internal CA Intermediate CA
          - /var/lib/step-ca/.step/certs/intermediate_ca.crt
          - /var/lib/step-ca/.step/secrets/intermediate_ca_key
      when: not intermediate_crl_markere.state.exists
      no_log: true

    - name: Marker für CRL Intermediate setzen
      ansible.builtin.file:
        path: /var/lib/step-ca/.step/.intermediate-crl-created
        state: touch
        owner: step-ca
        group: step-ca
        mode: "0600"
      when: not intermediate_crl_markere.state.exists


  handlers:
    - name: step-ca neustarten
      ansible.builtin.service:
        name: step-ca
        state: restarted
      listen: restart stepca